stages:
  - build
  - test
  - check

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - frontend/node_modules/
    - backend/.venv/
    - backend/__pycache__/

build-backend:
  stage: build
  image: python:3.11
  script:
    - apt-get update && apt-get install -y portaudio19-dev
    - cd backend
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
      - backend/.venv
    expire_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

test-backend:
  stage: test
  image: python:3.11
  script:
    - apt-get update && apt-get install -y portaudio19-dev
    - cd backend
    - source .venv/bin/activate
    - pip install -r requirements.txt
    - pytest tests --junitxml=result.xml
  artifacts:
    when: always
    reports:
      junit: backend/result.xml
    expire_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

build-frontend:
  stage: build
  image: node:latest
  script:
    - npm install
    - cd frontend
    - npm run lint
    - npm run format
  cache:
    paths:
      - frontend/node_modules/
    policy: pull-push
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

test-frontend:
  stage: test
  image: node:latest
  script:
    - npm install
    - cd frontend
    - npm run test
  artifacts:
    when: always
    paths:
      - frontend/test-reports
    expire_in: 1 week
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"

check-frontend:
  stage: check
  image: node:latest
  script:
    - export PORT=8081
    - npm install
    - cd frontend
    - npm run start --port=${PORT} &
    - npx wait-on http://localhost:${PORT} -t 30000
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"