version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: always
    command: sh -c "sleep 15; python3 app.py"  # sleep 15 seconds to wait for database
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      FLASK_ENV: development
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # contact David for password; include in a .env file in this directory with this variable

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - echodat:/var/lib/mysql
    ports:
      - "53346:3306"

volumes:
  echodat:
